import Head from 'next/head';
import AOS from 'aos';
import { useEffect } from 'react';
import { Banner, Header } from '@components/index';

export default function Home() {
    useEffect(() => {
        AOS.init();
    }, []);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />
            <main>
                <Banner />
                {/* <Section /> */}
            </main>
        </>
    );
}
